---
# This playbook deploys a simple nginx server.

- hosts: all
  become: yes

  tasks:

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        
    - name: install epel-release
      yum: name=epel-release state=latest

    - name: install nginx
      yum: name=nginx state=latest

    - name: restart and enable nginx
      service: name=nginx enabled=yes state=restarted
